export const VALID_SUPERMARKETS = [
  "esselunga",
  "conad",
  "lidl",
  "eurospin",
  "bennet",
  "auchan",
  "penny",
  "despar",
  "centesimo",
  "carrefouriper",
  "carrefourexpress",
  "prestofresco",
  "carrefourmarket",
  "gigante",
  "ins",
  "todis",
  "md",
  "crai",
  "paghipoco",
] as const

export type SupermarketName = (typeof VALID_SUPERMARKETS)[number]

export const SUPERMARKET_DISPLAY_NAMES: Record<SupermarketName, string> = {
  esselunga: "Esselunga",
  conad: "Conad",
  lidl: "Lidl",
  eurospin: "Eurospin",
  bennet: "Bennet",
  auchan: "Auchan",
  penny: "Penny Market",
  despar: "Despar",
  centesimo: "Centesimo",
  carrefouriper: "Carrefour Iper",
  carrefourexpress: "Carrefour Express",
  prestofresco: "Presto Fresco",
  carrefourmarket: "Carrefour Market",
  gigante: "Il Gigante",
  ins: "IN's Mercato",
  todis: "Todis",
  md: "MD Discount",
  crai: "Crai",
  paghipoco: "Pam Panorama",
}
