export const VALID_AISLES = [
  "frutta e verdura",
  "carne",
  "pesce",
  "salumi",
  "formaggi",
  "pane e prodotti da forno",
  "pasta",
  "riso",
  "legumi",
  "olio e condimenti",
  "uova",
  "latticini",
  "bevande",
  "vino",
  "birra",
  "acqua",
  "caffè",
  "zucchero e dolcificanti",
  "biscotti",
  "merendine",
  "cioccolato",
  "snack salati",
  "gelati",
  "surgelati",
  "conserve",
  "sughi e salse",
  "prodotti per la colazione",
  "bio",
  "senza glutine",
  "senza lattosio",
  "vegano",
  "vegetariano",
  "low carb",
  "proteico",
  "km 0",
  "artigianale",
  "prodotti locali",
  "per bambini",
  "cura per la casa",
  "cura per la persona",
  "animali domestici",
  "fai da te",
  "giardinaggio",
  "cura dell’auto",
  "prodotti per anziani",
  "estate",
  "autunno",
  "inverno",
  "primavera",
  "cambio stagione",
  "viaggi",
  "spesa base",
  "cene speciali",
  "compleanni",
  "feste bambini",
  "weekend",
  "fitness",
  "pronto subito",
  "abbigliamento",
  "elettrodomestici",
  "frutta secca",

  "fai da te",
  "bricolage",
];
